version: "2"

services:
  nginx:
    ports:
      - "3000:80"
    image: 'nginx:1.13.10'
    volumes:
      - './nginx:/etc/nginx/conf.d'
    depends_on:
      - gitea
      - frontend
    command: /bin/bash -c "sed 's/@KITSPACE_DOMAIN/${KITSPACE_DOMAIN}/g' /etc/nginx/conf.d/kitspace.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  frontend:
    ports:
      - "1234:3000"
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
  gitea:
    build:
      context: gitea
      dockerfile: Dockerfile
    environment:
      - ROOT_URL=http://gitea.${KITSPACE_DOMAIN}:3000/
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - ./volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3333:3000"
      - "2222:22"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
